# Generated by Django 3.0 on 2020-01-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_name',
            new_name='name',
        ),
    ]
